version: '3.10'
services:
  app:
    container_name: fastapi
    build: .
    volumes:
      - .:/to_do
    ports:
      - "9004:9004"
    depends_on:
      - db
    command: uvicorn to_do.main:app --reload --host 0.0.0.0 --port 9004
    env_file:
      - ./.env
    restart: always
  db:
    container_name: postgresql
    image: postgres:14-alpine
    env_file:
      - ./.env
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=to_do_db
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
